[schema]
filename = "supabase/database//**/*.sql"

[migrations]
filename = "supabase/migrations/*.sql"

[database]
host = "localhost"
port = 54322
user = "postgres"
password = "postgres"
dbname = "postgres"

[migra]
safe = true
privileges = false