SET search_path TO "public";

create table fruits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
);

create table countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    owner_id uuid default gen_random_uuid()
);

-- enable row level security for the fruit table
ALTER TABLE fruit ENABLE ROW LEVEL SECURITY;

-- create a policy that allows users to see only the rows they created
CREATE POLICY fruit_user ON fruit FOR SELECT USING (owner_id = auth.uid());