create schema if not exists "private";

create table "private"."fruit" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


create table "private"."profiles" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


create table "public"."fruit" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


CREATE UNIQUE INDEX fruit_name_key ON private.fruit USING btree (name);

CREATE UNIQUE INDEX profiles_name_key ON private.profiles USING btree (name);

CREATE UNIQUE INDEX fruit_name_key ON public.fruit USING btree (name);

alter table "private"."fruit" add constraint "fruit_name_key" UNIQUE using index "fruit_name_key";

alter table "private"."profiles" add constraint "profiles_name_key" UNIQUE using index "profiles_name_key";

alter table "public"."fruit" add constraint "fruit_name_key" UNIQUE using index "fruit_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION private.hello_world()
 RETURNS text
 LANGUAGE sql
AS $function$
  select 'Hello world';
$function$
;

CREATE OR REPLACE FUNCTION public.hello_world()
 RETURNS text
 LANGUAGE sql
AS $function$
  select 'Hello world';
$function$
;

