create table "public"."countries" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);

CREATE UNIQUE INDEX countries_name_key ON public.countries USING btree (name);

alter table "public"."countries" add constraint "countries_name_key" UNIQUE using index "countries_name_key";

