alter table "public"."fruit" drop constraint "fruit_name_key";

drop index if exists "public"."fruit_name_key";

drop table "public"."fruit";

create table "public"."fruits" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


CREATE UNIQUE INDEX fruits_name_key ON public.fruits USING btree (name);

alter table "public"."fruits" add constraint "fruits_name_key" UNIQUE using index "fruits_name_key";

